project_id = "ybvfsxsapsshhtqpvukr"

[functions.track-analytics]
verify_jwt = false

[functions.ai-concert-assistant]
verify_jwt = false

[functions.generate-news-sitemap]
verify_jwt = false

[functions.generate-artists-sitemap]
verify_jwt = false

[functions.generate-concerts-sitemap]
verify_jwt = false

[functions.generate-countries-sitemap]
verify_jwt = false

[functions.generate-blog-sitemap]
verify_jwt = false

[functions.generate-setlist-image]
verify_jwt = false

[functions.detect-user-country]
verify_jwt = false

[functions.spotify-api]
verify_jwt = false

[functions.firecrawl-scrape-prices]
verify_jwt = false

[functions.extract-prices-from-image]
verify_jwt = false
